### ISSUE TITLE
Rice University

### ISSUE THREAD

**Issue by devshahofficial** [stellis-labs/scripts#122]
**Goal**
1. Make a list of all colleges in this university and share the list in the comments.
2. Scrape the faculty directory for all colleges to obtain names, emails, and brief descriptions of each faculty.

**Data Required**
1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by aditya-kanala** [comment]
I'm interested.

**Comment by aditya-kanala** [comment]
List of Schools / Colleges in Rice University

1. School of Architecture
2. Jesse H. Jones Graduate School of Business
3. Susanne M. Glasscock School of Continuing Studies
4. George R. Brown School of Engineering and Computing
5. School of Humanities
6. The Shepherd School of Music
7. Wiess School of Natural Sciences
8. School of Social Sciences
