### ISSUE TITLE
Boston College (Chestnut Hill, MA)

### ISSUE THREAD

**Issue by krishvadhani19** [stellis-labs/scripts#124]
**Goal**
1. Make a list of all colleges in this university and share the list in the comments.
2. Scrape the faculty directory for all colleges to obtain names, emails, and brief descriptions of each faculty.

**Data Required**
1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by Thripura24** [comment]
I'm Interested.

**Comment by devshahofficial** [comment]
@Thripura24 assigning. Can you also comment the list of colleges in Boston college (only if any)

**Comment by Thripura24** [comment]
Sure, these are colleges in Boston college. 

1. Robert J. Morrissey College of Arts and Sciences
2. Boston College Law School 
3. James A. Woods, S.J. College of Advancing Studies 
4. School of Social Work 
5. Carroll School of Management
6. William F. Connell School of Nursing 
7. Carolyn A. and Peter S. Lynch School of Education and Human Development 
8. Gloria L. and Charles I. Clough School of Theology and Ministry  
9. Messina College.

**Comment by Thripura24** [comment]
completed scrapping data for this college
