### ISSUE TITLE
Ohio State University

### ISSUE THREAD

**Issue by devshahofficial** [stellis-labs/scripts#136]
**Goal**
1. Make a list of all colleges in this university and share the list in the comments.
2. Scrape the faculty directory for all colleges to obtain names, emails, and brief descriptions of each faculty.

**Data Required**
1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by yamini-pixel** [comment]
I'm interested!

**Comment by yaminimanral** [comment]
- [ ] College of Arts and Sciences
- [ ] Fisher College of Business
- [ ] College of Dentistry
- [ ] College of Education and Human Ecology
- [ ] College of Engineering
- [ ] Knowlton School of Architecture
- [ ] College of Food, Agricultural, and Environment Sciences
- [ ] School of Environment and Natural Resources
- [ ] Moritz College of Law
- [ ] College of Medicine
- [ ] School of health and Rehabilitation Sciences
- [ ] College of Nursing
- [ ] College of Optometry
- [ ] College of Pharmacy
- [ ] John Glen College if Public Affairs
- [ ] College of Public Health
- [ ] College of Social Work
- [ ] College of Veterinary Medicine

**Comment by yaminimanral** [comment]
[college_of_dentistry_the_ohio_state_university.csv](https://github.com/user-attachments/files/17970917/college_of_dentistry_the_ohio_state_university.csv)

**Comment by yaminimanral** [comment]
Done with this issue, please check and close. Thanks!
