### ISSUE TITLE
Purdue University

### ISSUE THREAD

**Issue by devshahofficial** [stellis-labs/scripts#137]
**Goal**
1. Make a list of all colleges in this university and share the list in the comments.
2. Scrape the faculty directory for all colleges to obtain names, emails, and brief descriptions of each faculty.

**Data Required**
1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by rastogi-neha** [comment]
Can I work on this?

**Comment by devshahofficial** [comment]
@rastogi-neha assigning! can you also comment the list of all universities under Pursue?

**Comment by devshahofficial** [comment]
@rastogi-neha use this link to join https://discord.gg/PhR59b3m

**Comment by rastogi-neha** [comment]
Hi @devshahofficial 
There are 12 Colleges and Schools under Purdue.
1. College of Agriculture
2. Daniels School of Business
3. College of Education
4. College of Engineering
5. Exploratory Studies
6. College of Health and Human Sciences
7. College of Liberal Arts
8. College of Pharmacy
9. Purdue Polytechnic Institute
10. College of Science
11. College of Veterinary Medicine
12. John Martinson Honors College

Scraped the 1st one-Agriculture

**Comment by rastogi-neha** [comment]
Completed all except College of Exploratory Studies 
(it has no Professors just advisors who help students choose their majors and minors)
