### ISSUE TITLE
Arizona State University

### ISSUE THREAD

**Issue by devshahofficial** [stellis-labs/scripts#145]
**Goal**
1. Make a list of all colleges in this university and share the list in the comments.
2. Scrape the faculty directory for all colleges to obtain names, emails, and brief descriptions of each faculty.

**Data Required**
1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by VedaUpasan** [comment]
I'm interested!

**Comment by devshahofficial** [comment]
@VedaUpasan assigned!

**Comment by VedaUpasan** [comment]
- [ ] 1. W. P. Carey School of Business website
- [ ] 2. Herberger Institute for Design and the Arts website
- [ ] 3. Ira A. Fulton Schools of Engineering
- [ ] 4. College of Global Futures
- [ ] 5. Thunderbird School of Global Management
- [ ] 6. Graduate College
- [ ] 7. College of Health Solutions 
- [ ] 8. Honors: Barrett, The Honors College at ASU
- [ ] 9. College of Integrative Sciences and Arts
- [ ] 10. New College of Interdisciplinary Arts and Sciences
- [ ] 11. Walter Cronkite School of Journalism and Mass Communication
- [ ] 12. Sandra Day O'Connor College of Law
- [ ] 13. The College of Liberal Arts and Sciences
- [ ] 14. Edson College of Nursing and Health Innovation
- [ ] 15. Watts College of Public Service and Community Solutions
- [ ] 16. Mary Lou Fulton Teachers College
- [ ] 17. University College

**Comment by VedaUpasan** [comment]
Scraped and ready for review.
