### ISSUE TITLE
The Massachusetts Life Sciences Center

### ISSUE THREAD

**Issue by devshahofficial** [stellis-labs/scripts#38]
### The Massachusetts Life Sciences Center

**Goal**
Scrape Stake holders directory to obtain names, emails, and brief descriptions.

**Data Required**
1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by vssubhasree** [comment]
I'm interested!

**Comment by devshahofficial** [comment]
@vssubhasree assigned!
