### ISSUE TITLE
MIT Venture Mentoring Service

### ISSUE THREAD

**Issue by devshahofficial** [stellis-labs/scripts#41]
### MIT Venture Mentoring Service

**Goal**
Scrape Stake holders directory to obtain names, emails, and brief descriptions.

**Data Required**
1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by VedaUpasan** [comment]
I'm interested

**Comment by devshahofficial** [comment]
@VedaUpasan assigned

**Comment by VedaUpasan** [comment]
This website contains information of VMS Leadership & Staff with name, title and some description. Their emails are not provided, but as it says MIT will try to get their emails from there. Does this information cover everything, or is there anything additional we need?

**Comment by VedaUpasan** [comment]
Scraped and ready for review.
