### ISSUE TITLE
Boston Academic Consortium

### ISSUE THREAD

**Issue by devshahofficial** [stellis-labs/scripts#42]
### Boston Academic Consortium

**Goal**
Scrape Stake holders directory to obtain names, emails, and brief descriptions.

**Data Required**
1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by DheerajChillamcharla** [comment]
I'm interested

**Comment by krishvadhani19** [comment]
Assigned @DheerajChillamcharla

**Comment by DheerajChillamcharla** [comment]
- The website contains information about the Boston consortium staff
- Also Board of Directors, each from different colleges that are part of the consortium. Their emails are provided but I think I can find them for their respective college websites probably. 
Is this information be enough or are we looking for anything else?

**Comment by DheerajChillamcharla** [comment]
Scraped and ready for review.

Couldn't find email for 3 people from their respective websites. For 2 of them I have mentioned what could be the email based on the pattern. Highlighted all 3 of them in yellow.
