### ISSUE TITLE
Boston College

### ISSUE THREAD

**Issue by devshahofficial** [stellis-labs/scripts#54]
**Goal**
1. Make a list of all colleges in this university and share the list in the comments.
2. Scrape the faculty directory for all colleges to obtain names, emails, and brief descriptions of each faculty.

**Data Required**
1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by VedaUpasan** [comment]
I'm interested

**Comment by VedaUpasan** [comment]
- [ ] Robert J. Morrissey College of Arts and Sciences
- [ ] Boston College Law School
- [ ] James A. Woods, S.J. College of Advancing Studies
- [ ] School of Social Work
- [ ] Carroll School of Management
- [ ] William F. Connell School of Nursing
- [ ] Carolyn A. and Peter S. Lynch School of Education and Human Development
- [ ] Gloria L. and Charles I. Clough School of Theology and Ministry
- [ ] Messina College
