### ISSUE TITLE
Wentworth Institute of Technology

### ISSUE THREAD

**Issue by devshahofficial** [stellis-labs/scripts#71]
**Goal**
1. Make a list of all colleges in this university and share the list in the comments.
2. Scrape the faculty directory for all colleges to obtain names, emails, and brief descriptions of each faculty.

**Data Required**
1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by Jaykumar-Kotiya** [comment]
I'm Interested

**Comment by devshahofficial** [comment]
@Jaykumar-Kotiya what is the status of this issue?

**Comment by Jaykumar-Kotiya** [comment]
I'm currently working On the issue, sorry for the delay in getting back to you! I was bed rest. It is almost done i will submit at the end of tomorrow. Hope that's ok

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jaykumar-Kotiya** [comment]
Scraped data and ready to use!
Number of school under WentWorth Institute of Technology

- [ ] School of Architecture & Design
- [ ] School of Computing & Data Science
- [ ] School of Engineering
- [ ] School of Management
- [ ] School of Sciences & Humanities
- [ ] Workforce Development
