### ISSUE TITLE
Emmanuel College

### ISSUE THREAD

**Issue by krishvadhani19** [stellis-labs/scripts#76]
**Goal**
1. Make a list of all colleges in this university and share the list in the comments.
2. Scrape the faculty directory for all colleges to obtain names, emails, and brief descriptions of each faculty.

**Data Required**
1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by aditya-kanala** [comment]
I am interested

**Comment by aditya-kanala** [comment]
List of colleges in Emmanuel College:
1. School of Business and Management
2. School of Education
3. School of Humanities and Social Sciences
4. Maureen Murphy Wilkens School of Nursing & Clinical Sciences
5. School of Science and Health

**Comment by devshahofficial** [comment]
@aditya-kanala assigned.

**Comment by devshahofficial** [comment]
@aditya-kanala what is the progress on this issue?

**Comment by aditya-kanala** [comment]
I am just left to scrap the faculty details. Should be done in a couple of days.
There were lot of unexpected elements that had to be taken care of.
Apologies for the delay.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
