### ISSUE TITLE
Northeastern Kostas Research Institute for Homeland Security

### ISSUE THREAD

**Issue by krishvadhani19** [stellis-labs/scripts#8]
Goal
Scrape Stake holders directory to obtain names, emails, and brief descriptions.

Data Required

1. Name
2. Email
3. Description (title, department, etc.)

Submit xlxs or csv.

**Comment by VedaUpasan** [comment]
I'm Interested

**Comment by VedaUpasan** [comment]
Scraped and ready for review.
